# Generated by Django 5.2.1 on 2025-07-17 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='researcher',
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='researcherprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('research_fellow', 'Research Fellow'), ('postdoc', 'Post-Doctoral Researcher'), ('phd_student', 'PhD Student'), ('masters_student', 'Masters Student'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated list of keywords', null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers/pdfs/')),
                ('wos_ut_id', models.CharField(blank=True, help_text='Web of Science Accession Number (UT)', max_length=50, null=True, unique=True)),
                ('venue_h_index', models.FloatField(blank=True, null=True)),
                ('venue_i10_index', models.FloatField(blank=True, null=True)),
                ('venue_impact_factor', models.FloatField(blank=True, help_text='Journal Impact Factor from WoS JCR', null=True)),
                ('abstract_readability_score', models.FloatField(blank=True, null=True)),
                ('title_length', models.IntegerField(blank=True, null=True)),
                ('keyword_relevance_score', models.FloatField(blank=True, null=True)),
                ('tf_idf_vector', models.JSONField(blank=True, help_text='TF-IDF vector or lightweight embedding of paper text', null=True)),
                ('actual_citation_count', models.IntegerField(default=0, help_text='Current number of citations from Web of Science')),
                ('last_wos_update', models.DateTimeField(blank=True, help_text='Timestamp of last successful WoS citation fetch', null=True)),
                ('predicted_citations_2y', models.IntegerField(blank=True, help_text='Predicted citations in 2 years', null=True)),
                ('prediction_confidence_interval_low', models.IntegerField(blank=True, null=True)),
                ('prediction_confidence_interval_high', models.IntegerField(blank=True, null=True)),
                ('visibility_category', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('key_feature_contributions', models.JSONField(blank=True, help_text='JSON object mapping feature names to their contribution scores', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.DeleteModel(
            name='CitationPrediction',
        ),
        migrations.DeleteModel(
            name='ResearchPaper',
        ),
    ]
