# Generated by Django 5.2.1 on 2025-08-18 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename of the uploaded document', max_length=255)),
                ('title', models.TextField(help_text='Extracted or generated title from the document')),
                ('abstract', models.TextField(blank=True, help_text='Extracted abstract or summary from the document', null=True)),
                ('keywords', models.JSONField(default=list, help_text='List of extracted keywords from the document')),
                ('file_size', models.PositiveIntegerField(help_text='Size of the original file in bytes')),
                ('file_type', models.CharField(help_text='File extension (pdf, docx, txt)', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'filename'], name='user_resear_user_id_34860d_idx'), models.Index(fields=['uploaded_at'], name='user_resear_uploade_1a30c9_idx')],
                'unique_together': {('user', 'filename')},
            },
        ),
    ]
