# Generated by Django 5.2.1 on 2025-08-28 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_researchpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOSDummyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wos_uid', models.CharField(help_text='Web of Science UID of the paper', max_length=255)),
                ('original_citations', models.IntegerField(help_text='Original citation count of the paper')),
                ('dummy_predicted_citations', models.IntegerField(help_text='30% of original citations, rounded')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wos_dummy_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WOS Dummy Prediction',
                'verbose_name_plural': 'WOS Dummy Predictions',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
