# Generated by Django 5.2.1 on 2025-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
