# Generated by Django 5.2.1 on 2025-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_wosdummyprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosdummyprediction',
            name='dummy_percentage',
            field=models.IntegerField(default=26, help_text='Random percentage used for the prediction'),
        ),
        migrations.AlterField(
            model_name='wosdummyprediction',
            name='dummy_predicted_citations',
            field=models.IntegerField(help_text='Citations predicted based on the dummy percentage'),
        ),
    ]
