# Generated by Django 5.2.1 on 2025-08-28 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_wosdummyprediction_dummy_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOSLightGBMPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wos_uid', models.CharField(help_text='Web of Science UID of the paper', max_length=255)),
                ('original_citations', models.IntegerField(help_text='Original citation count of the paper')),
                ('light_gbm_percentage', models.IntegerField(default=21, help_text='Random percentage used for the prediction')),
                ('light_gbm_predicted_citations', models.IntegerField(help_text='Citations predicted based on the LightGBM percentage')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wos_light_gbm_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WOS LightGBM Prediction',
                'verbose_name_plural': 'WOS LightGBM Predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.DeleteModel(
            name='WOSDummyPrediction',
        ),
    ]
