# Generated by Django 5.2.1 on 2025-08-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_paper_authors_paper_category_paper_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOSSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('search_field', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('json_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wos_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
