# Generated by Django 5.2.1 on 2025-08-28 16:59

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_woslightgbmprediction_delete_wosdummyprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='citation_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='google_scholar_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='h_index',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='i10_index',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='Format: 0000-0000-0000-0000', max_length=50),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='position',
            field=models.CharField(blank=True, help_text='e.g., PhD Candidate, Assistant Professor', max_length=255),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile_picture_path),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='research_gate_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Comma-separated list of interests'),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='woslightgbmprediction',
            name='light_gbm_percentage',
            field=models.IntegerField(default=17, help_text='Random percentage used for the prediction'),
        ),
    ]
