# Generated by Django 5.2.1 on 2025-08-28 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_researcherprofile_citation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='authors',
            field=models.JSONField(blank=True, default=list, help_text='List of extracted authors from the document.'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='predicted_citations',
            field=models.IntegerField(blank=True, help_text='Predicted citation count for the next 2 years.', null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='prediction_confidence_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='prediction_confidence_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='publication_year',
            field=models.IntegerField(blank=True, help_text='Extracted publication year.', null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(blank=True, default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='woslightgbmprediction',
            name='light_gbm_percentage',
            field=models.IntegerField(default=19, help_text='Random percentage used for the prediction'),
        ),
        migrations.AlterField(
            model_name='woslightgbmprediction',
            name='predicted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
