# Generated by Django 5.2.1 on 2025-08-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_researchpaper_authors_researchpaper_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woslightgbmprediction',
            name='light_gbm_percentage',
            field=models.IntegerField(help_text='Random percentage used for the prediction'),
        ),
    ]
