# Generated by Django 5.2.1 on 2025-08-28 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_woslightgbmprediction_light_gbm_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOSRidgePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wos_uid', models.CharField(help_text='Web of Science UID of the paper', max_length=255)),
                ('predicted_citations', models.IntegerField(help_text='Citations predicted by the Ridge model')),
                ('ci_low', models.FloatField(blank=True, help_text='Lower bound of the 95% confidence interval', null=True)),
                ('ci_high', models.FloatField(blank=True, help_text='Upper bound of the 95% confidence interval', null=True)),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wos_ridge_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WOS Ridge Prediction',
                'verbose_name_plural': 'WOS Ridge Predictions',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
