# Generated by Django 5.2.1 on 2025-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_wosridgeprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='light_gbm_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage used for dummy LightGBM prediction', null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='light_gbm_predicted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='light_gbm_predicted_citations',
            field=models.IntegerField(blank=True, help_text='Dummy LightGBM prediction', null=True),
        ),
    ]
