# Generated by Django 5.2.1 on 2025-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_researchpaper_light_gbm_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='light_gbm_percentage',
            field=models.IntegerField(blank=True, help_text='[DEPRECATED] No longer used.', null=True),
        ),
    ]
