# Generated by Django 5.2.1 on 2025-09-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_researchpaper_light_gbm_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaperLightGBMPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_gbm_predicted_citations', models.IntegerField(help_text='Citations predicted by the LightGBM model')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('research_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_gbm_predictions', to='user.researchpaper')),
            ],
            options={
                'verbose_name': 'Research Paper LightGBM Prediction',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaperRidgePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_citations', models.IntegerField(help_text='Citations predicted by the Ridge model')),
                ('ci_low', models.FloatField(blank=True, help_text='Lower bound of the 95% confidence interval', null=True)),
                ('ci_high', models.FloatField(blank=True, help_text='Upper bound of the 95% confidence interval', null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('research_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridge_predictions', to='user.researchpaper')),
            ],
            options={
                'verbose_name': 'Research Paper Ridge Prediction',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
